#!/bin/bash -e

source_dir="$1"
if [ ! -e $source_dir ]; then
  echo "Need to provide a directory containing nodejs application source"
  exit 1
fi

mkdir -p /opt/openshift/cartridge
chown nodejs_app:nodejs_app /opt/openshift/cartridge

pushd /opt/openshift/cartridge >/dev/null

cp -vRf $source_dir/* .
foreman start

popd > /dev/null